// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "goa simple sample": Application Media Types
//
// Command:
// $ goagen
// --design=design
// --out=$(GOPATH)\goa-sample
// --version=v1.3.1

package app

// example Response (default view)
//
// Identifier: application/vnd.integer+json; view=default
type Integer struct {
	// id
	ID int `form:"id" json:"id" yaml:"id" xml:"id"`
}
