// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "goa simple sample": swagger TestHelpers
//
// Command:
// $ goagen
// --design=design
// --out=$(GOPATH)\goa-sample
// --version=v1.3.1

package test
